# -- language model
nwe: 400
nlayers_rnn: 2
nhid_rnn: 400
dropoute: 0.2
dropouti: 0.4
dropoutl: 0.2
dropouth: 0.2
dropouto: 0.5
tied_weights: true
wd_lm: 0.00005
# -- optim
lr: 0.003
lr_decay: 0.1
patience: 20
