dataroot: /local/delasalles/dataset/drlm_iclr_2019/S2
mode: prediction
min_freq: 3
# -- xp
xproot: /local/delasalles/xp/fgm/repro_iclr
name: drlm_s2
# -- language model
tie_weights: true
dropoute: 0.2
dropouti: 0.4
dropoutl: 0.2
dropouth: 0.2
dropouto: 0.5
# -- DRLM parameters
nzt: 10
no_transition: false
nhid_zt: 0
nlayers_zt: 1
res_zt: false
wd_t: 0.0000001
# -- optim
lr: 0.003
wd: 0.00005
patience: 10
